
title: "TikTok Top"
description: "Lista influencerów"


url: "https://artemhord.github.io"
baseurl: "/wwwlab1"

collections:
  influencers:
    output: true
    permalink: /influencers/:title/

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge

assets:
  sources: ["assets"]

