# Tytuł i opis strony
title: "TikTok Top"
description: "Lista influencerów"

# Podstawowe adresy URL
url: ""         #
baseurl: "/wwwlab1"

# Konfiguracja kolekcji
collections:
  influencers:
    output: true
    permalink: /influencers/:title/

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge

assets:
  sources: ["assets"]

